### ISSUE TITLE
SuperDynamicLighting render issue

### ISSUE THREAD

**Issue by mariano-mena** [Neill3d/OpenMoBu#1]
Hi Neill.
When rendering a scene with SuperDynamicLighting shader applied to any kind of object (even the native mobu primitives) those object's texture renders as black after the first 100 rendered frames. No matter what FPS, but it happens from frame 100.
That issue affects any of the textures channels (Diffuse, Specular, NormalMap).

**Comment by Neill3d** [comment]
It looks like after 100 frames, motionbuild is doing a texture recaching, and a solution for that is to put "Force Update Textures" flag under a shader properties.
