### ISSUE TITLE
Hi Neill ! Facecap2023

### ISSUE THREAD

**Issue by EmissiveAnim** [Neill3d/OpenMoBu#12]
Hope you're going well,
I was wondering if you have the time to compile the FaceCapReceiver Device for motionbuilder 2023 ?
Much thanks for all you have done !
Cheers

**Comment by Neill3d** [comment]
I think it have to be already uploaded in binary folder for 2023, check it out please - https://github.com/Neill3d/OpenMoBu/tree/master/bin/x64/plugins_2023

**Comment by EmissiveAnim** [comment]
Hello, the device_facecap.dll is not working on my motionbuilder2023.
It says it's not made to work on windows because of an error...basically.. 
error 0xc000012f

**Comment by Neill3d** [comment]
I've updated the file, please try again

**Comment by EmissiveAnim** [comment]
Hi Sergueï, 
I'm still having the same error msg with the new .dll

**Comment by Neill3d** [comment]
I've updated one more time. If that doesn't help, then probably your sdk differs from what I have... what we can do with that, you can try to compile your self or if you don't know how to do that, I can try to compile with your OpenReality SDK if you could send me these SDK files - share a zipped OpenRealitySDK folder from your mobu 2023

**Comment by EmissiveAnim** [comment]
Hi ! it sadly gives me the same error message... and I don't know how to compile (I really need to learn how to with VS). If you want you can compare the OpenRealitySDK I have ( regular licenced mobu 2023 release ) , I've uploaded the files here : https://we.tl/t-nnAGBNq29Q

**Comment by Neill3d** [comment]
ok, thank you for sharing your SDK files, I've uploaded a new binary for 2023

**Comment by EmissiveAnim** [comment]
Thanks for your efforts but...  still no luck, I get the same error message.
I'm on Windows 10 pro.

**Comment by EmissiveAnim** [comment]
here is the log : Application started
------------------------------------------------------------------------------
In MOTIONBUILDER_PLUGIN_PATH environment setting, the C:\Program Files (x86)\OpenMoBu\bin\x64\plugins directory does not exist.

Licensing library is trusted      : "C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\AdskLicensingSDK_6.dll"
Desktop Licensing Runtime Version : 6.3.1.44
Desktop Licensing API version     : 6.3.1.44
Desktop Licensing executable path : C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64
Desktop Licensing Adlm log path   : C:\flexlm\Adlm.err
Desktop Licensing product key     : 727O1
Desktop Licensing product version : 2023.0.0.F
Desktop Licensing feature id      : MOBPRO
initialize: GetInstance (Success)

Desktop Licensing timeout         : i=0 r=0 c=0

adlsdkGetAuthStatus: status Success

Desktop Licensing pre-release     : 0
Desktop Licensing method          : METHOD_USER
Desktop Licensing behavior        : BEHAVIOR_USER
Desktop Licensing usage           : USAGE_USER
Desktop Licensing expir. status   : LICENSE_EXPDATE_TIMESTAMP
MotionBuilder compiled against Qt 5.15.2, runtime linked to Qt 5.15.2
Using OpenGL: 4.6.0 NVIDIA 516.94

Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\basic.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\deck.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\DynamicLightingInternal.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\DynamicLightingShadowInternal.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\fbmcs3800.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\fbxmb.dll
MotionBuilder compiled against FBXSDK 2020.3 Release (0)
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\glove.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\gpi.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\hikhost2013.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\hikhost2014.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\hikhost2016.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\kcuda.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\kvectorgraphics.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\ltc.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\magnetic.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\midi.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\network.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\PhysicsConstraint.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\script.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\script_embedded_code.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\script_external_file.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\sound.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\spaceball.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\toolanimation.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\toolbroadcast.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\toolbrowsing.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\toolcharacter.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\toolconstraint.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\tooldesktop.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\tooldevice.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\toolfacial.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\toolfcurve.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\toolmanipulator.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\toolmedia.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\toolnle.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\tooloptical.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\toolprofiling.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\toolpropertybrowser.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\toolpythonide.dll
KPythonServer: Listening on port 4242...
KPythonServer: Serving on 1 address.
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\toolshaders.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\tooltimelinex.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\tooltrigger.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\toolweighting.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\trigger.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\voice.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\wacomtable.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\PhysicsEngine\Engine_ODE.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\extensions\PhysicsEngine\Engine_PhysX.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\plugins\device_facecap.dll
      Failed with error 193: %1 nÆest pas une application Win32 valide.
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\plugins\krtfilter.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\plugins\ormotionbuilder_shelf.dll
Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\plugins\perforce.dll
Using CUDA device 0: NVIDIA GeForce RTX 2080 Ti
Execute: C:\Program Files\Autodesk\MotionBuilder 2023\bin\config\Python\ToolManager.py
Execute: C:\Program Files\Autodesk\MotionBuilder 2023\bin\config\PythonStartup\BatchProcess.py
Execute: C:\Program Files\Autodesk\MotionBuilder 2023\bin\config\PythonStartup\BatchTool.py
Execute: C:\Program Files\Autodesk\MotionBuilder 2023\bin\config\PythonStartup\CharacterSelectAndKey.py
Execute: C:\Program Files\Autodesk\MotionBuilder 2023\bin\config\PythonStartup\FBX Export.py
Execute: C:\Program Files\Autodesk\MotionBuilder 2023\bin\config\PythonStartup\KeyboardShortcutsEditor.py
Execute: C:\Program Files\Autodesk\MotionBuilder 2023\bin\config\PythonStartup\PyTestStarter.py
0 FBX MB extension plug-ins found!

![image](https://user-images.githubusercontent.com/111854815/195659819-2d7fe2e9-c377-4583-8e27-53865cbe2b58.png)
I noticed it says incorrect image on top, could it be related to the icon you use for the device ?

**Comment by Neill3d** [comment]
just tried in mobu 2023, it works for me. and the error you have is still about a wrong build version, are you using a file from binary x64 2023 on github ? I put a file on google drive to be sure that we are talking about the same file - https://drive.google.com/file/d/1uqt1vHOAp2Ujp9pjOK9nOS6WbMitgiaV/view?usp=sharing
`Load Library: C:\Program Files\Autodesk\MotionBuilder 2023\bin\x64\plugins\device_facecap.dll
Failed with error 193: %1 nÆest pas une application Win32 valide.`
 And this is a path where a wrong file is located

**Comment by EmissiveAnim** [comment]
Hey good news the .dll inside the zip is working ! (And I checked again : the one located here https://github.com/Neill3d/OpenMoBu/tree/master/bin/x64/plugins_2023  is not !!)
Much much thanks !

**Comment by Neill3d** [comment]
I see, so all that time it was a broken uploaded file on github, that's weird, but I'm glad that we sort that out. I have to prepare an updated installer package with binaries to avoid such issues.
