### ISSUE TITLE
relation box problem

### ISSUE THREAD

**Issue by cmercado-streumon** [Neill3d/OpenMoBu#14]
hello I install the last version of the plugin for MoBu 2022, but it doesnt install all the feature, the quartenion relations are not installed correctly and I got this error when I open MoBu.
[
![image](https://user-images.githubusercontent.com/129539982/229184228-cfbe0df8-19c7-4405-8505-2f851a08146f.png)
](url)

**Comment by Neill3d** [comment]
Hello, I think that's related to having a broken plugin file or compiled to a different Motionbuilder version. Do you use installation package or directly download binaries from repository ?
